//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public partial class SteamVR_Actions
    {
        
        private static SteamVR_Action_Single p_robotInput_MoveRightClaw;
        
        private static SteamVR_Action_Single p_robotInput_MoveLeftClaw;
        
        private static SteamVR_Action_Vector2 p_robotInput_MoveUpRoll;
        
        private static SteamVR_Action_Vector2 p_robotInput_MoveForwardSide;
        
        private static SteamVR_Action_Single p_robotInput_Pitch;
        
        private static SteamVR_Action_Single p_robotInput_Yaw;
        
        private static SteamVR_Action_Pose p_robotInput_Head;
        
        public static SteamVR_Action_Single robotInput_MoveRightClaw
        {
            get
            {
                return SteamVR_Actions.p_robotInput_MoveRightClaw.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single robotInput_MoveLeftClaw
        {
            get
            {
                return SteamVR_Actions.p_robotInput_MoveLeftClaw.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Vector2 robotInput_MoveUpRoll
        {
            get
            {
                return SteamVR_Actions.p_robotInput_MoveUpRoll.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Vector2 robotInput_MoveForwardSide
        {
            get
            {
                return SteamVR_Actions.p_robotInput_MoveForwardSide.GetCopy<SteamVR_Action_Vector2>();
            }
        }
        
        public static SteamVR_Action_Single robotInput_Pitch
        {
            get
            {
                return SteamVR_Actions.p_robotInput_Pitch.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Single robotInput_Yaw
        {
            get
            {
                return SteamVR_Actions.p_robotInput_Yaw.GetCopy<SteamVR_Action_Single>();
            }
        }
        
        public static SteamVR_Action_Pose robotInput_Head
        {
            get
            {
                return SteamVR_Actions.p_robotInput_Head.GetCopy<SteamVR_Action_Pose>();
            }
        }
        
        private static void InitializeActionArrays()
        {
            Valve.VR.SteamVR_Input.actions = new Valve.VR.SteamVR_Action[] {
                    SteamVR_Actions.robotInput_MoveRightClaw,
                    SteamVR_Actions.robotInput_MoveLeftClaw,
                    SteamVR_Actions.robotInput_MoveUpRoll,
                    SteamVR_Actions.robotInput_MoveForwardSide,
                    SteamVR_Actions.robotInput_Pitch,
                    SteamVR_Actions.robotInput_Yaw,
                    SteamVR_Actions.robotInput_Head};
            Valve.VR.SteamVR_Input.actionsIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.robotInput_MoveRightClaw,
                    SteamVR_Actions.robotInput_MoveLeftClaw,
                    SteamVR_Actions.robotInput_MoveUpRoll,
                    SteamVR_Actions.robotInput_MoveForwardSide,
                    SteamVR_Actions.robotInput_Pitch,
                    SteamVR_Actions.robotInput_Yaw,
                    SteamVR_Actions.robotInput_Head};
            Valve.VR.SteamVR_Input.actionsOut = new Valve.VR.ISteamVR_Action_Out[0];
            Valve.VR.SteamVR_Input.actionsVibration = new Valve.VR.SteamVR_Action_Vibration[0];
            Valve.VR.SteamVR_Input.actionsPose = new Valve.VR.SteamVR_Action_Pose[] {
                    SteamVR_Actions.robotInput_Head};
            Valve.VR.SteamVR_Input.actionsBoolean = new Valve.VR.SteamVR_Action_Boolean[0];
            Valve.VR.SteamVR_Input.actionsSingle = new Valve.VR.SteamVR_Action_Single[] {
                    SteamVR_Actions.robotInput_MoveRightClaw,
                    SteamVR_Actions.robotInput_MoveLeftClaw,
                    SteamVR_Actions.robotInput_Pitch,
                    SteamVR_Actions.robotInput_Yaw};
            Valve.VR.SteamVR_Input.actionsVector2 = new Valve.VR.SteamVR_Action_Vector2[] {
                    SteamVR_Actions.robotInput_MoveUpRoll,
                    SteamVR_Actions.robotInput_MoveForwardSide};
            Valve.VR.SteamVR_Input.actionsVector3 = new Valve.VR.SteamVR_Action_Vector3[0];
            Valve.VR.SteamVR_Input.actionsSkeleton = new Valve.VR.SteamVR_Action_Skeleton[0];
            Valve.VR.SteamVR_Input.actionsNonPoseNonSkeletonIn = new Valve.VR.ISteamVR_Action_In[] {
                    SteamVR_Actions.robotInput_MoveRightClaw,
                    SteamVR_Actions.robotInput_MoveLeftClaw,
                    SteamVR_Actions.robotInput_MoveUpRoll,
                    SteamVR_Actions.robotInput_MoveForwardSide,
                    SteamVR_Actions.robotInput_Pitch,
                    SteamVR_Actions.robotInput_Yaw};
        }
        
        private static void PreInitActions()
        {
            SteamVR_Actions.p_robotInput_MoveRightClaw = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/RobotInput/in/MoveRightClaw")));
            SteamVR_Actions.p_robotInput_MoveLeftClaw = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/RobotInput/in/MoveLeftClaw")));
            SteamVR_Actions.p_robotInput_MoveUpRoll = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/RobotInput/in/MoveUpRoll")));
            SteamVR_Actions.p_robotInput_MoveForwardSide = ((SteamVR_Action_Vector2)(SteamVR_Action.Create<SteamVR_Action_Vector2>("/actions/RobotInput/in/MoveForwardSide")));
            SteamVR_Actions.p_robotInput_Pitch = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/RobotInput/in/Pitch")));
            SteamVR_Actions.p_robotInput_Yaw = ((SteamVR_Action_Single)(SteamVR_Action.Create<SteamVR_Action_Single>("/actions/RobotInput/in/Yaw")));
            SteamVR_Actions.p_robotInput_Head = ((SteamVR_Action_Pose)(SteamVR_Action.Create<SteamVR_Action_Pose>("/actions/RobotInput/in/Head")));
        }
    }
}
