//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_RobotInput : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single MoveRightClaw
        {
            get
            {
                return SteamVR_Actions.robotInput_MoveRightClaw;
            }
        }
        
        public virtual SteamVR_Action_Single MoveLeftClaw
        {
            get
            {
                return SteamVR_Actions.robotInput_MoveLeftClaw;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MoveUpRoll
        {
            get
            {
                return SteamVR_Actions.robotInput_MoveUpRoll;
            }
        }
        
        public virtual SteamVR_Action_Vector2 MoveForwardSide
        {
            get
            {
                return SteamVR_Actions.robotInput_MoveForwardSide;
            }
        }
        
        public virtual SteamVR_Action_Single Pitch
        {
            get
            {
                return SteamVR_Actions.robotInput_Pitch;
            }
        }
        
        public virtual SteamVR_Action_Single Yaw
        {
            get
            {
                return SteamVR_Actions.robotInput_Yaw;
            }
        }
        
        public virtual SteamVR_Action_Pose Head
        {
            get
            {
                return SteamVR_Actions.robotInput_Head;
            }
        }
    }
}
